services:
  db:
    image: postgres:16-alpine
    container_name: nexledger_db
    environment:
      POSTGRES_DB: nexledger
      POSTGRES_USER: nexledger
      POSTGRES_PASSWORD: nexledger
    ports:
      - "5432:5432"
    volumes:
      - nexledger_db_data:/var/lib/postgresql/data

volumes:
  nexledger_db_data:
